"""
Set up a redirect URL for OAuth so you can get tokens.
For Production, we need an HTTPS URL.
"""
import sys
from pathlib import Path

def setup_redirect_guide():
    """Guide user to set up redirect URL."""
    print("=" * 80)
    print("Setting Up OAuth Redirect URL for Production")
    print("=" * 80)
    print()
    print("eBay requires a redirect URL to be configured before you can get OAuth tokens.")
    print("Even for manual token generation, you need to set this up once.")
    print()
    print("=" * 80)
    print("Option 1: Use ngrok (Free HTTPS Tunnel) - RECOMMENDED")
    print("=" * 80)
    print()
    print("1. Download ngrok:")
    print("   https://ngrok.com/download")
    print()
    print("2. Run ngrok in a separate terminal:")
    print("   ngrok http 8080")
    print()
    print("3. Copy the HTTPS URL (e.g., https://abc123.ngrok.io)")
    print()
    print("4. Go to: https://developer.ebay.com/my/keys")
    print("   - Click 'Production' tab")
    print("   - Click 'User Tokens' for Production app")
    print("   - Scroll to 'Get a Token from eBay via Your Application'")
    print("   - Click '+ Add eBay Redirect URL'")
    print("   - Fill in:")
    print("     Display Title: Production OAuth")
    print("     Your auth accepted URL1: https://YOUR_NGROK_URL.ngrok.io/callback")
    print("     (Replace YOUR_NGROK_URL with your actual ngrok URL)")
    print("   - Check 'OAuth Enabled'")
    print("   - Click 'Save'")
    print()
    print("5. Keep ngrok running, then try 'Sign in to Production' again")
    print()
    print("=" * 80)
    print("Option 2: Use a Public Webhook Service")
    print("=" * 80)
    print()
    print("You can use httpbin.org (but it might not work for Production):")
    print()
    print("1. Go to: https://developer.ebay.com/my/keys")
    print("2. Click 'User Tokens' for Production")
    print("3. Click '+ Add eBay Redirect URL'")
    print("4. Fill in:")
    print("   Display Title: Production OAuth")
    print("   Your auth accepted URL1: https://httpbin.org/anything")
    print("   Check 'OAuth Enabled'")
    print("   Click 'Save'")
    print()
    print("5. Try 'Sign in to Production' again")
    print()
    print("=" * 80)
    print("Option 3: Use Your Own Domain (If You Have One)")
    print("=" * 80)
    print()
    print("If you have a domain with HTTPS:")
    print("1. Use: https://yourdomain.com/ebay-callback")
    print("2. Add it in Developer Console as above")
    print()
    print("=" * 80)
    print("After Setting Up Redirect URL")
    print("=" * 80)
    print()
    print("1. Go back to 'Get a User Token Here' section")
    print("2. Select 'OAuth (new security)'")
    print("3. Click 'Sign in to Production'")
    print("4. It should work now!")
    print()
    print("The redirect URL is just a one-time setup requirement.")
    print("You don't actually need to use it for manual token generation,")
    print("but eBay requires it to be configured.")
    print()

if __name__ == "__main__":
    setup_redirect_guide()
