"""
Verify sandbox test user setup and provide next steps.
"""
from config import Config

def main():
    print("=" * 80)
    print("Sandbox Test User Verification")
    print("=" * 80)
    print()
    
    config = Config()
    print(f"Environment: {config.EBAY_ENVIRONMENT.upper()}")
    print(f"Test User: TESTUSER_manbot")
    print()
    
    print("=" * 80)
    print("Next Steps to Fix 403 Errors:")
    print("=" * 80)
    print()
    print("1. VERIFY TEST USER EXISTS:")
    print("   - On the Sandbox page, click 'Create test users'")
    print("   - Check if 'TESTUSER_manbot' is listed")
    print("   - If not, create it with seller privileges")
    print()
    print("2. LOG INTO SANDBOX AS TEST USER:")
    print("   - Go to: https://sandbox.ebay.com")
    print("   - Sign in with: TESTUSER_manbot")
    print("   - Complete seller registration if prompted")
    print("   - Accept seller terms and conditions")
    print()
    print("3. TEST API WITH API EXPLORER:")
    print("   - On the Sandbox page, click 'Test My API Requests'")
    print("   - Or go to: https://developer.ebay.com/my/api-explorer")
    print("   - Select 'Sandbox' environment")
    print("   - Try: GET /sell/inventory/v1/inventory_item")
    print("   - Use your OAuth token")
    print("   - This will show if the issue is with the token or account")
    print()
    print("4. CHECK IF LISTING CREATION STILL WORKS:")
    print("   - You successfully created a listing earlier")
    print("   - Try creating another listing to verify")
    print("   - If it works, the token is fine for listing creation")
    print("   - The 403 might only affect read operations")
    print()
    print("=" * 80)
    print("Quick Test:")
    print("=" * 80)
    print()
    print("Since listing creation worked earlier, let's test if it still works:")
    print("   python -c \"from ebay_listing import eBayListingManager; m = eBayListingManager(); print('Listing manager initialized successfully')\"")
    print()
    print("Or try the Setup UI:")
    print("   python -m streamlit run setup_ui.py")
    print()
    print("The 403 errors on read operations might be normal for sandbox,")
    print("but listing creation (write operations) should still work.")

if __name__ == "__main__":
    main()
